### DataSet ###
data_path: data
load_col:
  inter: [user_id, item_id, timestamp]
checkpoint_dir: 'baseline'
train_neg_sample_args: ~
MAX_ITEM_LIST_LENGTH: 50


topk: [5, 10]
metrics: ["Recall","MRR","NDCG","Hit","Precision"]
