### DataSet ###
data_path: data
load_col:
  inter: [user_id, item_id, timestamp]
checkpoint_dir: data/beauty
train_neg_sample_args: ~
MAX_ITEM_LIST_LENGTH: 50

topk: [5, 10]
metrics: ["Recall","MRR","NDCG","Hit","Precision"]

# train_batch_size: 32
# eval_batch_size: 256

# n_layers: 2
# n_heads: 2
# hidden_size: 64
# inner_size: 256
# hidden_dropout_prob: 0.5
# attn_dropout_prob: 0.5
# hidden_act: 'gelu'
# layer_norm_eps: 1e-12
# initializer_range: 0.02
# loss_type: 'CE'